{{- if .Values.instrumentation }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Values.name }}
spec:
  exporter:
    endpoint: {{ .Values.global.otel.endpoint }}
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  {{- $language := .Values.instrumentation }}
  {{- $envVars := dict "name" "OTEL_SERVICE_NAME" "value" .Values.name }}
  {{- with $language }}
  {{- $envVars := append $envVars (dict "name" "OTEL_LOGS_EXPORTER" "value" "otlp") }}
  {{- end }}
  {{ $language }}:
    env:
      - name: OTEL_SERVICE_NAME
        value: {{ .Values.name }}
      - name: OTEL_LOGS_EXPORTER
        value: otlp
{{- end }}
