{{- if .Values.bucket.enabled }}
---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: bucket
metadata:
  name: devxp-{{ .Values.name }}
  namespace: {{ include "namespace" . }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.name }}
spec:
  forProvider:
    acl: {{ .Values.bucket.acl }}
    locationConstraint: {{ .Values.bucket.locationConstraint }}
    objectLockEnabledForbucket: {{ .Values.bucket.objectLockEnabledForbucket }}
  providerConfigRef:
    name: {{ .Values.providerConfigRef }}
{{- end }}


