---
# Source: devxp-app/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
  annotations:
    backstage.io/kubernetes-id: test
  labels:
    app: test
    istio-injection: enabled
    kubernetes.io/metadata.name: test
spec: {}
status: {}
---
# Source: devxp-app/templates/resource-quota.yaml
kind: ResourceQuota
apiVersion: v1
metadata:
  name: test
  namespace: test
  labels:
    app: test
    version: "latest"
    backstage.io/kubernetes-id: test
    helm.sh/chart: devxp-app-0.2.7
    app.kubernetes.io/name: devxp-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argocd
spec: 
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.cpu: "1"
    requests.memory: 1Gi
---
# Source: devxp-app/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: test
  labels:
    app: test
    version: "latest"
    backstage.io/kubernetes-id: test
    helm.sh/chart: devxp-app-0.2.7
    app.kubernetes.io/name: devxp-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argocd
---
# Source: devxp-app/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  - destinationrules
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
# Source: devxp-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
  labels:
    app: test
    version: "latest"
    backstage.io/kubernetes-id: test
    helm.sh/chart: devxp-app-0.2.7
    app.kubernetes.io/name: devxp-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app: test
  ports:
  - name: tcp-node
    port: 80
    targetPort:  8080
    protocol: TCP
---
# Source: devxp-app/templates/hpa.yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: test
  namespace: test
  labels:
    app: test
    version: "latest"
    backstage.io/kubernetes-id: test
    helm.sh/chart: devxp-app-0.2.7
    app.kubernetes.io/name: devxp-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argocd
spec:
  scaleTargetRef:  
    name: test
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
# Source: devxp-app/templates/analysis.yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: test
  namespace: test
  labels: 
    app: test
    version: "latest"
    backstage.io/kubernetes-id: test
    helm.sh/chart: devxp-app-0.2.7
    app.kubernetes.io/name: devxp-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argocd
spec:
  # this analysis template requires a service name and namespace to be supplied to the query
  args:
  - name: service
  - name: namespace
  metrics:
  - name: success-rate
    initialDelay: 30s
    interval: 20s
    successCondition: result[0] > 0.95
    provider:
      prometheus:
        address: http://prometheus-server.monitoring
        query: >+
          sum(irate(istio_requests_total{
            reporter="source",
            destination_service=~"test.test.svc.cluster.local",
            response_code!~"5.*"}[40s])
          )
          /
          sum(irate(istio_requests_total{
            reporter="source",
            destination_service=~"test.test.svc.cluster.local"}[40s])
          )
---
# Source: devxp-app/templates/destination-rule.yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test
  namespace: test
spec:
  host: test.test.svc.cluster.local
  subsets:
  - name: canary   # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
    labels:        # labels will be injected with canary rollouts-pod-template-hash value
      app: test
  - name: stable   # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
    labels:        # labels will be injected with canary rollouts-pod-template-hash value
      app: test
---
# Source: devxp-app/templates/peer-authentication.yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: test-strict
  namespace: test
spec:
  selector:
    matchLabels:
      app: test
  mtls:
    mode: STRICT
---
# Source: devxp-app/templates/argo-rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test
  namespace: test
  labels: 
    app: test
    version: "latest"
    backstage.io/kubernetes-id: test
    helm.sh/chart: devxp-app-0.2.7
    app.kubernetes.io/name: devxp-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argocd
  annotations:
    {}
spec:
  revisionHistoryLimit: 5
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      dynamicStableScale: true
      trafficRouting:
        istio:
          virtualService:
            name: test        # required
            routes:
            - primary                 # required
          destinationRule:
            name: test    # required
            canarySubsetName: canary    # required
            stableSubsetName: stable    # required
      maxSurge: "25%"
      maxUnavailable: 0
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels: 
        app: test
        version: "latest"
        backstage.io/kubernetes-id: test
        helm.sh/chart: devxp-app-0.2.7
        app.kubernetes.io/name: devxp-app
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: argocd
    spec:
      serviceAccountName: test
      containers:
      - name: test
        image: :latest
        imagePullPolicy: IfNotPresent
        env:
        envFrom:
        ports:
        - name: http
          containerPort: 8080
        resources: 
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      nodeSelector: 
        {}
      affinity: 
        {}
      tolerations: 
        []
  minReadySeconds: 30
---
# Source: devxp-app/templates/image-pull-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ghcr-secret
spec:
  encryptedData:
    .dockerconfigjson: AgDGBqpFurhI5BktCG/olnD7r2MuhAel/zkL1IL0BxrcaDUmR8JUf3TEkMqKbiRgb9iKYcwX7zVOXI4xDJeiyWyWDbckn8Yc+RBTw7qpKhh3kMUasPVo9blEcrKq4HjSEAEKapegBDT+H1LhjUToDoqwXVmGFEVYpiHtb0OA0OCtUuDZ2dYD4cLpMSVgZ/8hRfilRdD4PqXD+k1NEVZfRgKGl9fV0mazKm9e7w0rRI1brryhWx9+VZcvSi6RLHiELX7VOObxxjQ0W4gCuHKDRztgHoNDR+KVNum6YpVz8vOXQ/XpBxlASundsryNBAVcPwv0HYQDmsNFfMwXaLkLA+Hg6frWXi1CJvSrJc45U8RQ2sAfbCN6QQw1r6O+Lgqc2hmWnx3RzOva6zIq2UqUNRDrKxn99zZUCU4GpmVLFnj08ogq0p86zUXqzA6o1Qz1KRZu2S0QaQQyMquN4vqByXRfbXrgG5rtQRALsRG3o7q7OfOoy1sa1mF6kMyktpbawE7eT0k0FGPdjEtgg5FzLD88pj5OphL1aNTVzgSLVMpT0KY8GHVlB5AlMxz+ilB0bfSs+S5fGsY5u4iOpUAioAQ2lZH/aK8tMMug4pCRsYvDD6AUWlCupzGHhjVNeWDvhGpUG8anpr0htCxqLAGLJaMGV/hcuwbRzdxgKbPjqd/HFpzwi9ZN17IN1vtQhGm3xR781WTBAeLzU7XykzLh8VuUPhS6c8vdNsXXXYubSXrCAddAycXc5YThp/TzfOlPzn/3kkQZZRKUs3Qp393djTaEG75W/CpnQXG4Pnvk9a4swUCm2ZwNYCZdCjBccutcahlKa8mNG4sDeYbpLOG4ZICo2MuKNoJG2DqmemSUGKeThSyhW8v2CjoKqKhGSKbpUjI43c5dK4TueC88DYMZGX2TF5yOtXwmQbjsutAd3n2ELujLpg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ghcr-secret
    type: kubernetes.io/dockerconfigjson
---
# Source: devxp-app/templates/virtual-service.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
  namespace: test
  annotations:
    link.argocd.argoproj.io/external-link: https://test.devxp-tech.io
  labels:
    app: test
    version: latest
    backstage.io/kubernetes-id: test
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - test.devxp-tech.io
  http:
  - name: primary
    route:
    - destination:
        subset: stable  # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
        host: test.test.svc.cluster.local
      weight: 100
    - destination:
        host: test.test.svc.cluster.local
        subset: canary # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
      weight: 0
---
# Source: devxp-app/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "devxp-app-test-connection"
  labels:
    app: test
    version: "latest"
    backstage.io/kubernetes-id: test
    helm.sh/chart: devxp-app-0.2.7
    app.kubernetes.io/name: devxp-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argocd
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['devxp-app:8080']
  restartPolicy: Never
