# Default values for devxp-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# --name is the github repository name of this application deploy
name: ""
nameOverride: {}
# --fullnameOverride full override the name
fullnameOverride: {}

global:
  # --cluster Set Cluster Name
  cluster: cluster.local
  # --commonLabels set common labels for all resources
  commonLabels: {}
  # team_name: dev
  # --prometheus set prometheus server url
  prometheus:
    server: http://prometheus-community-kube-prometheus.monitoring.svc.cluster.local:9090 #set new endpoint
  # -- Network
  network:
    # --domain Set Default Domain
    domain: devxp-tech.io

# --namespace
namespace:
  enabled: true
  labels: {}
  annotations: {}
  # sidecar.jaegertracing.io/inject: "true"

# --deployment Disabled Deployment
deployment:
  # --enabled default false
  enabled: false
  annotations: {}

# --argoRollouts enable Argo Rollouts Deployment
argoRollouts:
  # --Specifies whether a resource quota should be created
  enabled: true
  revisionHistoryLimit: 5
  analyses:
    enabled: true
    successCondition: 0.95
    failureLimit: 3
  dynamicStableScale: true
  strategy:
    steps:
      - setWeight: 5
      - pause:
          duration: 10s
      - setWeight: 20
      - pause:
          duration: 10s
      - setWeight: 40
      - pause:
          duration: 10s
      - setWeight: 60
      - pause:
          duration: 10s
      - setWeight: 80
      - pause:
          duration: 10s

# cronjobs list of cronjobs to be included in the application
cronjobs:
  # --suspend used to disable all cronjobs in the list
  suspend: false
  # --list is an array of spec for create multiples cronjobs
  list:
    []
    # - name: cron1
    #   schecule: "* * * * *"
    #   command:
    #     - echo "ok"

# --consumers is the object to configure an array of consumers
consumers:
  # --terminationGracePeriodSeconds configures terminationGracePeriodSeconds
  terminationGracePeriodSeconds: 30
  # --list is the array of consumer definition
  list:
    []
    # - name: required
    #   command:
    #     - required

# --service
service:
  # --service.port Define the Service Port
  port:
    name: tcp-node
    # --port is the port your application runs under
    port: 80
  annotations: {}
  labels: {}
  externalDns:
    enabled: false
  # --service An abstract way to expose an application running on a set of Pods as a network service.
  type: ClusterIP
  nodePort: {}

# --istio Set default Istio
istio:
  # enable istio-injection label on namespace
  enabled: true
  # --istio.virtualServices Set Istio virtualServices parameters
  virtualServices:
    # --istio.virtualServices.enable Set Istio virtualServices enabled
    enabled: true
    custom:
      hosts: []
  # --PeerAuthentication defines how traffic will be tunneled (or not) to the sidecar.
  peerAuthentication:
    # --enable peerAuthentication
    enabled: true
    # --set peerAuthentication mode, values (UNSET, DISABLE, PERMISSIVE, STRICT)
    mode: PERMISSIVE
  # --gateways set default gateway for virtual-service
  gateways: istio-ingress/istio-ingressgateway

# --ServiceAccount A service account provides an identity for processes that run in a Pod, about more: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  name: {}
  # --Specifies whether a service account should be created
  enabled: true
  # --Annotations to add to the service account
  annotations: {}
  # --serviceAccount.annotations Automont Service Account Token
  automountServiceAccountToken: true

# --replicaCount is used when autoscaling.enabled is false to set a manually number of pods
replicaCount: 1
# --autoscaling is the main object of autoscaling
autoscaling:
  # --enabled is the flag to sinalize this funcionality is enabled
  enabled: true
  # --minReplicas is the number of mim pods to be running
  minReplicas: 1
  # --maxReplicas is the number of maximum scaling pods
  maxReplicas: 2
  # --targetCPUUtilizationPercentage is the percentage of cpu when reached to scale new pods
  targetCPUUtilizationPercentage: 80
  # --targetMemoryUtilizationPercentage is the percentage of memoty when reached to scale new pods
  targetMemoryUtilizationPercentage: 80
  # --customRules is a place to customize your application autoscaler using the original API available at: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  customRules:
    []
    # - type: Resource
    #   resource:
    #     name: memory
    #     target:
    #       type: Utilization
    #       averageUtilization: 20

container:
  # --port is the port your application runs under
  port: 8080
  readOnlyRootFilesystem: true

  # --image is the object to specify the image to run in the deployment
image:
  # --repository: is the registry of your application ex:556684128444.dkr.ecr.us-east-1.amazonaws.com/YOU-APP-ECR-REPO-NAME
  # if empty this helm will auto generate the image using aws.registry/values.name:values.image.tag
  repository: ""
  # --pullPolicy is the prop to setup the behavior of pull police. options is: IfNotPresent \| allways
  pullPolicy: IfNotPresent
  # --especify the tag of your image to deploy
  tag: "latest"

# --imagePullSecrets secret used to download image on private container registry
imagePullSecrets:
  # --imagePullSecrets.enabled create secret do pull docker images in private registrys
  enabled: true
  name: ghcr-secret

# --resources set deployment resources
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

# --probe
probe:
  # --probe.enabled Enable liveness and readiness probe
  enabled: true

livenessProbe:
  httpGet:
    path: /health-check/liveness
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health-check/readiness
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
# --A security context defines privilege and access control settings for a Pod or Container. About more: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext:
  {}
  # --fsGroup: 2000
securityContext:
  {}
  # --capabilities:
  # --drop:
  # ---ALL
  # --readOnlyRootFilesystem: true
  # --runAsNonRoot: true
  # --runAsUser: 1000

envs:
  []
  # examples:
  # please note that when the value is a number, you must quote the value to cast to string!
  # - name: ENVIROMENT
  #   value: dev
  # - name: ENVIROMENT1
  #   value: true

envFrom:
  []
  # examples:
  # please note that when the value is a number, you must quote the value to cast to string!
  # - configMapRef
  #     name: postgres-configs

# --volumes specifies pod volumes
volumes:
  []
  # - name: sensitive-config
  #   secret:
  #     secretName: app-secrets

# --volumeMounts specifies where Kubernetes will mount Pod volumes
volumeMounts:
  []
  # - name: sensitive-config
  #   mountPath: /sensitive-config/
  #   readOnly: true

# --sealedSecrets enable creation of a secret to pull images
sealedSecrets:
  # --enabled create a Sealed Secret in the namespace
  enabled: true
  # --encryptedData hash to create secret
  encryptedData: AgDGBqpFurhI5BktCG/olnD7r2MuhAel/zkL1IL0BxrcaDUmR8JUf3TEkMqKbiRgb9iKYcwX7zVOXI4xDJeiyWyWDbckn8Yc+RBTw7qpKhh3kMUasPVo9blEcrKq4HjSEAEKapegBDT+H1LhjUToDoqwXVmGFEVYpiHtb0OA0OCtUuDZ2dYD4cLpMSVgZ/8hRfilRdD4PqXD+k1NEVZfRgKGl9fV0mazKm9e7w0rRI1brryhWx9+VZcvSi6RLHiELX7VOObxxjQ0W4gCuHKDRztgHoNDR+KVNum6YpVz8vOXQ/XpBxlASundsryNBAVcPwv0HYQDmsNFfMwXaLkLA+Hg6frWXi1CJvSrJc45U8RQ2sAfbCN6QQw1r6O+Lgqc2hmWnx3RzOva6zIq2UqUNRDrKxn99zZUCU4GpmVLFnj08ogq0p86zUXqzA6o1Qz1KRZu2S0QaQQyMquN4vqByXRfbXrgG5rtQRALsRG3o7q7OfOoy1sa1mF6kMyktpbawE7eT0k0FGPdjEtgg5FzLD88pj5OphL1aNTVzgSLVMpT0KY8GHVlB5AlMxz+ilB0bfSs+S5fGsY5u4iOpUAioAQ2lZH/aK8tMMug4pCRsYvDD6AUWlCupzGHhjVNeWDvhGpUG8anpr0htCxqLAGLJaMGV/hcuwbRzdxgKbPjqd/HFpzwi9ZN17IN1vtQhGm3xR781WTBAeLzU7XykzLh8VuUPhS6c8vdNsXXXYubSXrCAddAycXc5YThp/TzfOlPzn/3kkQZZRKUs3Qp393djTaEG75W/CpnQXG4Pnvk9a4swUCm2ZwNYCZdCjBccutcahlKa8mNG4sDeYbpLOG4ZICo2MuKNoJG2DqmemSUGKeThSyhW8v2CjoKqKhGSKbpUjI43c5dK4TueC88DYMZGX2TF5yOtXwmQbjsutAd3n2ELujLpg==

# --ResourceQuota provides constraints that limit aggregate resource consumption per namespace
quota:
  # --Specifies whether a resource quota should be created
  enabled: true
  # --resources Specifies the hard resources
  resources:
    hard:
      # --requests.cpu Specifies the request cpu
      requests.cpu: "1"
      requests.memory: 1Gi
      limits.cpu: "2"
      limits.memory: 2Gi

# --migration Set liquibase migration
migration:
  # -- migration.enable liquibase migration
  enabled: false

monitoring:
  # -- If enabled, create default actuator path and metrics
  actuator:
    enabled: false
    port:
      name: tcp-metrics
      port: 8080
      targetPort: 8080
    path: /actuator/prometheus
  rules:
    # -- If enabled, create PrometheusRule resource with app recording rules
    enabled: false
    # -- Include alerting rules
    alerting: true
    # -- Alternative namespace to create recording rules PrometheusRule resource in
    namespace: null
    # -- Additional annotations for the rules PrometheusRule resource
    annotations: {}
    # -- Additional labels for the rules PrometheusRule resource
    labels: {}
    # -- Additional groups to add to the rules file
    additionalGroups: []
    # - name: additional-app-rules
    #   rules:
    #     - record: job:app_request_duration_seconds_bucket:sum_rate
    #       expr: sum(rate(app_request_duration_seconds_bucket[1m])) by (le, job)
    #     - record: job_route:app_request_duration_seconds_bucket:sum_rate
    #       expr: sum(rate(app_request_duration_seconds_bucket[1m])) by (le, job, route)
    #     - record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
    #       expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (node, namespace, pod, container)

  # Alerting rules for monitoring app
  alerts:
    # -- If enabled, create PrometheusRule resource with app alerting rules
    enabled: false
    # -- Alternative namespace to create alerting rules PrometheusRule resource in
    namespace: null
    # -- Additional annotations for the alerts PrometheusRule resource
    annotations: {}
    # -- Additional labels for the alerts PrometheusRule resource
    labels: {}

# ServiceMonitor configuration
  serviceMonitor:
    # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
    enabled: true
    # -- Alternative namespace for ServiceMonitor resources
    namespace: null
    # -- Namespace selector for ServiceMonitor resources
    namespaceSelector: {}
    # -- ServiceMonitor annotations
    annotations: {}
    # -- Additional ServiceMonitor labels
    labels: {}
    # -- ServiceMonitor scrape interval
    interval: 60s
    # -- ServiceMonitor path to scrape
    path: /metrics
    # -- ServiceMonitor scrape timeout in Go duration format (e.g. 15s)
    scrapeTimeout: 15s
    # -- ServiceMonitor relabel configs to apply to samples before scraping
    # https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#relabelconfig
    relabelings: []
    # -- ServiceMonitor will use http by default, but you can pick https as well
    scheme: http
    # -- ServiceMonitor will use these tlsConfig settings to make the health check requests
    # tlsConfig: null
