{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-migration
  namespace: {{ include "namespace" . }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    sidecar.istio.io/inject: "false"
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Values.name }}-migration
          image: {{ .Values.image.repository }}-migration:{{ .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- with .Values.envs }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
          envFrom:
          {{- with .Values.envFrom }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
{{- end }}