{{- if .Values.namespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "namespace" . }}
  annotations:
    backstage.io/kubernetes-id: {{ .Values.name }}
  {{- with .Values.nsAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.nsLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec: {}
status: {}
{{- end }}