{{- if .Values.namespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "namespace" . }}
  {{- with .Values.nsAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.nsLabels }}
  labels:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec: {}
status: {}
{{- end }}