{{- if .Values.global.istio }}
  {{- if .Values.peerAuthentication.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .Values.name }}-{{ .Values.peerAuthentication.mode }}
  namespace: {{ include "namespace" . }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  mtls:
    mode: {{ .Values.peerAuthentication.mode }}
  {{- end }}
{{- end }}