{{- if .Values.quota.enabled }}
kind: ResourceQuota
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
  labels: {{- include "devxp-app.labels" . | nindent 4 }}
spec: {{ toYaml .Values.quota.resources | nindent 2 }}
{{- end }}