---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.name }}.{{ .Values.network.domain }}
  labels:
    app: {{ .Values.name }}
    version: {{ .Values.image.tag }}
    backstage.io/kubernetes-id: {{ .Values.name }}
spec:
  type: {{ .Values.network.service.type }}
  selector:
    app: {{ .Values.name }}
  {{- if eq .Values.network.service.type "ClusterIP" }}
  ports:
  - name: tcp-node
    port: {{ .Values.network.service.port }}
    targetPort:  {{ .Values.container.port }}
    protocol: TCP
  {{- end }}
  {{- if eq .Values.network.service.type "NodePort" }}
  ports:
    - port: {{ .Values.network.service.port }}
      targetPort: {{ .Values.container.port }}
      nodePort: 30007
  {{- end }}