---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
  labels: {{- include "devxp-app.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- if .Values.externalDns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.name }}.{{ .Values.network.domain }}
  {{- end }}
  {{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
  {{- if eq .Values.service.type "ClusterIP" }}
  ports:
  - name: {{ .Values.service.port.name }}
    port: {{ .Values.service.port.port }}
    targetPort:  {{ .Values.container.port }}
    protocol: TCP
  {{- end }}
  {{- if eq .Values.service.type "NodePort" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      nodePort: {{ .Values.service.nodePort }}
  {{- end }}



