---
# Source: devxp-dev/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teste
  namespace: develop
  labels:
    app: teste
    version: "latest"
    backstage.io/kubernetes-id: teste
    helm.sh/chart: devxp-dev-0.0.3
    app.kubernetes.io/name: devxp-dev
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argocd
  annotations:
    {}
---
# Source: devxp-dev/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: teste
  namespace: develop
  labels:
    app: teste
    version: "latest"
    backstage.io/kubernetes-id: teste
    helm.sh/chart: devxp-dev-0.0.3
    app.kubernetes.io/name: devxp-dev
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app: teste
  ports:
  - name: tcp-node
    port: 80
    targetPort:  8080
    protocol: TCP
---
# Source: devxp-dev/templates/deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste
  namespace: develop
  labels:
    app: teste
    version: "latest"
    backstage.io/kubernetes-id: teste
    helm.sh/chart: devxp-dev-0.0.3
    app.kubernetes.io/name: devxp-dev
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argocd
  annotations:
    {}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: teste
  template:
    metadata:
      labels:
        app: teste
        version: "latest"
        backstage.io/kubernetes-id: teste
        helm.sh/chart: devxp-dev-0.0.3
        app.kubernetes.io/name: devxp-dev
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: argocd
    spec:
      serviceAccountName: teste
      containers:
      - name: teste
        image: "ghcr.io/devxp-tech/teste:latest"
        imagePullPolicy: IfNotPresent
        env:
            []
        envFrom:
            []
        ports:
        - name: http
          containerPort: 8080
        resources: 
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
        volumeMounts: 
            []
      nodeSelector: 
        {}
      affinity: 
        {}
      tolerations: 
        []
      volumes: 
        []
  minReadySeconds: 30
---
# Source: devxp-dev/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "devxp-dev-test-connection"
  labels:
    app: teste
    version: "latest"
    backstage.io/kubernetes-id: teste
    helm.sh/chart: devxp-dev-0.0.3
    app.kubernetes.io/name: devxp-dev
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argocd
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['devxp-dev:8080']
  restartPolicy: Never
