{{- if .Values.monitoring.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
  labels: {{ include "devxp-app.labels" . | nindent 4 }}
  annotations: {{- .Values.monitoring.serviceMonitor.annotations | toYaml | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
    - {{ include "namespace" . }}
  selector:
    matchLabels:
      {{- include "devxp-app.selectorLabels" $ | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.port.name }}
      {{- with .interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .path }}
      path: {{ . }}
      {{- end }}
      {{- with .scheme }}
      scheme: {{ . }}
      {{- end }}
      {{- with .tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}