{{- if .Values.monitoring.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
  labels: {{ include "devxp-app.labels" . | nindent 4 }}
  annotations: {{- .Values.monitoring.serviceMonitor.annotations | toYaml | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
    - {{ include "namespace" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  endpoints:
    {{- include "service-monitor" ( dict "monitor" .Values.monitoring "port" .Values.service.port.name "actuator" .Values.actuator ) | indent 4 }}
{{- end }}