name: Auto Assign 🦾

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    uses: devxp-tech/.github/.github/workflows/auto-assign.yaml@main
    secrets: inherit
    with:
      assignees: diegoluisi
      numOfAssignee: 1

  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: ffittschen/pr-branch-labeler@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Label Chart
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true