name: Helm Diff 🤖

on:
  workflow_dispatch:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  helm-diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Generate Results from Main
      run: |
        for p in $(ls -l charts | awk '{print $9}'); do helm template charts/$p -f charts/$p/values-ci.yaml > charts/$p/$p-result.yaml ; done

    - name: Upload cluster-bootstrap
      uses: actions/upload-artifact@v3
      with:
        name: cluster-bootstrap-result.yaml
        path: charts/cluster-bootstrap/cluster-bootstrap-result.yaml

    - name: Checkout 🛎️
      uses: actions/checkout@v4

    - name: Download cluster-bootstrap-result.yaml
      uses: actions/download-artifact@v3
      with:
        name: cluster-bootstrap-result.yaml

    - name: Print the final result
      shell: bash
      run: |
        value=`cat cluster-bootstrap-result.yaml`
        echo The result is $value


    - name: Diff
      continue-on-error: true
      run: diff --side-by-side --suppress-common-lines --ignore-space-change charts/devxp-dev/results.yaml results_new.yaml > diff.yaml && echo "Contents are identical"

    # - name: PR comment with file
    #   uses: thollander/actions-comment-pull-request@v2
    #   with:
    #     comment_tag: show_diff
    #     filePath: diff.yaml
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}